version: '3.1'

services:

  erpdb:
    image: postgres
    hostname: erpdb
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    volumes:
      - ./workshopdb/postdata:/var/lib/postgresql/data
    ports:
      - "15432:5432"
    networks:
      - postgre
  
  dbadmin:
    image: dpage/pgadmin4
    hostname: dbadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: mack@freedomaws.com
      PGADMIN_DEFAULT_PASSWORD: example
    volumes:
      - ./workshopdb/postadmin:/var/lib/pgadmin
    networks:
      - postgre
    ports:
      - "4480:80"

networks:
  postgre:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.202.0.0/24
