version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    volumes:
      - ./postdata:/var/lib/postgresql/data
    ports:
      - "22500:22"
      - "5430:5432"
  
